### ISSUE TITLE
How to perform the network differential analysis?

### ISSUE THREAD

**Issue by BinhongLiu** [kevinmcgregor/mdine#1]
Hi,
    mdine is really a useful tool for network building!
   I've found the method to create the network method and code [here](https://github.com/kevinmcgregor/mdine/blob/master/doc/mdine-vignette.pdf). But I could not find the code to perform the network differential analysis like the Figure 5 in your [paper](https://academic.oup.com/bioinformatics/article/36/6/1840/5614428). Could you share the related code to do the analysis, please? 
Thanks!
Hongbin Liu

**Comment by kevinmcgregor** [comment]
Hi Hongbin,

Yes, the code is here:

https://github.com/kevinmcgregor/crohns_analysis

Cheers,
Kevin
