### ISSUE TITLE
invsigma0/1 is not positive definite

### ISSUE THREAD

**Issue by YAYA530** [kevinmcgregor/mdine#11]
<img width="783" alt="截屏2022-02-26 上午3 05 08" src="https://user-images.githubusercontent.com/57092408/155773358-f4993b95-ad6f-4b82-b7c3-8b65fde9ef18.png">
Why always showed above information and the estimated precision matrix are all NA.

**Comment by kevinmcgregor** [comment]
It's impossible for me to tell without more information.
