### ISSUE TITLE
installation in Mac

### ISSUE THREAD

**Issue by gc26762524** [kevinmcgregor/mdine#12]
Hi mdine developers,

I have installed the rstan but still encountered following errors:

Downloading GitHub repo kevinmcgregor/mdine@HEAD
Error in utils::download.file(url, path, method = method, quiet = quiet,  : 
  download from 'https://api.github.com/repos/kevinmcgregor/mdine/tarball/HEAD' failed

Also tried to download the repository and do install.packages() from source, but still failed.

Please advise if similar issues for other users. Thank you.

Best,
Cheng

**Comment by gc26762524** [comment]
Also tried in different networks and different Mac laptop, all installations were not succeed.

**Comment by kevinmcgregor** [comment]
Hi Cheng,

Can you show the output of `sessionInfo()` ?  Also, are you using a mac with M1 or M2 chip?

Kevin

**Comment by gc26762524** [comment]
> sessionInfo()
R version 4.1.1 (2021-08-10)
Platform: x86_64-apple-darwin17.0 (64-bit)
Running under: macOS Mojave 10.14.6

Matrix products: default
BLAS:   /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/4.1/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] devtools_2.4.3 usethis_2.1.5  remotes_2.4.2 

loaded via a namespace (and not attached):
 [1] magrittr_2.0.3    pkgload_1.2.4     R6_2.5.1          rlang_1.0.2       fastmap_1.1.0    
 [6] tools_4.1.1       pkgbuild_1.3.0    sessioninfo_1.2.2 cli_3.3.0         withr_2.5.0      
[11] ellipsis_0.3.2    rprojroot_2.0.2   lifecycle_1.0.1   crayon_1.5.1      processx_3.5.2   
[16] purrr_0.3.4       callr_3.7.0       fs_1.5.2          ps_1.6.0          curl_4.3.2       
[21] testthat_3.1.1    memoise_2.0.1     glue_1.6.2        cachem_1.0.6      compiler_4.1.1   
[26] desc_1.4.0        prettyunits_1.1.1


I tried the installation in two Mac laptop, one is 2017 Macpro and one is 2022 MacAir (M1 chip). Neither worked though.

Thank you in advance

**Comment by kevinmcgregor** [comment]
First can you try updating to the current version of R and try installing again? 

Also, what error do you get when you try to install from source?

Kevin

**Comment by gc26762524** [comment]
Hi Kevin,

Thank you for your replies. By some googling too that I increased the allowed timeout by options(timeout=99999) for big repository download, and it worked eventually. Hope that will help others with similar issue.

My feeling is the mdine is a perfect tool for microbiome network comparison between groups but the it is somehow difficult to follow for me that I don't find much tutorial information though. I find it in another issue that one can replicate the plots in the original paper by using the the scripts from the repository crohns_analysis. With that to follow, I have a few additional questions/discussions:

1. what is the ref column in the input data? 2. it is not very straightforward for me to start with my own data, like a OTU/feature table. The input data seems to be specific to a numeric matrix. 3. I can only run the data with probably less than 25 features. When more features are included, it gives me error like "Exception: validate transformed params: invsigma0 is not positive definite.  (in 'model_mn_model' at line 53)". Do you know why that. 4. The computation seems heavy when running 1000 iterations. My laptop can't handle it. Do you suggest run the analysis in a server? 5. I noticed your example in the paper is using family level taxonomy. Do you think species level network analysis will still work? Thank you in advance for helping out at your convenience.

Best,
Cheng

**Comment by kevinmcgregor** [comment]
Glad you got it working.

There's a vignette PDF available under https://github.com/kevinmcgregor/mdine/tree/master/doc

The reference column is the reference category in the denominator of the additive log-ratio transformation.  This can be anything you want, the results for the remaining networks should not be very sensitive to this.

What's your sample size?  If you get that error for more than 25 features then it might be due to inadequate sample size.  Also, I would definitely recommend running it on a cluster; it's very computationally heavy.

You can run on lower taxonomic levels than species, but it might not work so well for species with a large number of zero counts.  You might need to filter those out first.
