### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by carolynePearl** [kevinmcgregor/mdine#4]
Hello,

Is it possible for you to provide a simple tutorial for this package please? Otherwise i installed the package successfully.

**Comment by kevinmcgregor** [comment]
There's a vignette [here](https://github.com/kevinmcgregor/mdine/blob/master/doc/mdine-vignette.pdf).

If you want to reproduce the figures from the paper, you can run code from [here](https://github.com/kevinmcgregor/crohns_analysis)

**Comment by carolynePearl** [comment]
thank you let try it out with my data
