### ISSUE TITLE
for metabolites+pathways+microbiome

### ISSUE THREAD

**Issue by khemlalnirmalkar** [kevinmcgregor/mdine#7]
Hi,
Can I use this tool to see the co-occurrence between metabolites (normalized z scores)+pathways (relative abundance)+microbiome (relative abundance) data?

Thanks,
Khem

**Comment by kevinmcgregor** [comment]
Hi Khem,

No, it wouldn't be able to handle the metabolites in this way, since the assumed distribution for the data is multinomial which would not be appropriate for z-scores.

Cheers,
Kevin

**Comment by khemlalnirmalkar** [comment]
Hi Kevin,
Thanks for your comment,
then is there any other way to use the metabolites data?
Shall i convert from z scores to relative abundance?

Khem

**Comment by kevinmcgregor** [comment]
I don't think it will be possible to include the metabolites in the network, since the data that go into the outcome matrix Y must be from a sequencing-based (count-based) platform.  Though to be honest I'm not very familiar with metabolic platforms so I don't know what the data look like.

Kevin

**Comment by khemlalnirmalkar** [comment]
Okay Thanks, Kevin for your input,
I guess i need to look for some other tools,
Khem
